# This is a basic workflow to help you get started with Actions

name: Staging CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, release/* ]
  pull_request:
    branches: [ develop, release/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Flutter github actions
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # or: 'stable' or 'dev' or 'beta'

      - name: Configure Flutter and build codes
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web
    
      - name: Deploy Netlify 🚀
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build/web'
          draft: false
          comment-on-commit: true

      - name: Deploy Firebase 🚀
        working-directory: build/web
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}